apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-ingress
  namespace: sock-shop
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - sock.nuel-dev.me
  #   - grafana.nuel-dev.me
  #   - prometheus.nuel-dev.me
  #   secretName: tls-secret
  rules:
  - host: sock.nuel-dev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80

  - host: grafana.nuel-dev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80          

  - host: prometheus.nuel-dev.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090

# tls:
#   - hosts:
#       - prometheus.nuel-dev.me
#       - sock.nuel-dev.me
#       - grafana.nuel-dev.me
#     secretName: tls-secret