name: k8s

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy-sockapp-on-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
  
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: update kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name sock-shop
          kubectl config set-context --current --namespace=sock-shop

      - name: Install Cert-Manager CRDs
        run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
            

      - name: Run Deployment files
        run: |
          kubectl apply -f ./deploy/.

      - name: Add Helm Charts
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm repo update