name: terraform

on:
  push:
    branches: [ "terraform" ]

  workflow_dispatch:

jobs:
  deploy-sockapp-on-eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # install Terraform in workflow        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'          

      # set AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create S3 bucket
        run: aws s3 mb s3://nuel-capstone-backend  
        
      - name: Create eks cluster  
        run: |
          terraform -chdir=terraform/ init
          terraform -chdir=terraform/ apply --auto-approve

      - name: update kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name sock-shop
          kubectl create namespace sock-shop

      - name: Add Helm Charts
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add jetstack https://charts.jetstack.io --force-update
